name: Basic QA Pipeline

# When to run the pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3

    - name: Run a simple test script
      run: |
        echo "Hello from GitHub Actions!"
        if [ 2 -eq 2 ]; then
          echo "Test passed ✅"
        else
          echo "Test failed ❌"
          exit 1
        fi
